@baseUrl = http://127.0.0.1:8000
# printer 1
#@ip = 192.168.1.7
#@apiKey = N9BjnWFdBOGCAhNlF9EmepEJ6PAklXDye0pEhRUBYxs

# printer 2
#@ip = 192.168.1.8
#@apiKey = XXTbEpJhyc7DglBQcxzodvch3YbmeJl9Uv6R6PHhgfY

# printer 3
#@ip = 192.168.1.9:80
#@apiKey = 0sEcfqbyAUqaBX-LySJAHY7xANs-_ge1_L7JnpdWz4Y

# printer 4
#@ip = 192.168.1.10
#@apiKey = LwkjwuybUCIRZIbdaaQ3UGRykEAyOP6nGkp6MJphzX4

#printer home
@ip = 10.0.0.18
@apiKey = hFswwTnAYX5NloewqL4MHfW_LyTqF7_GZ3qPB4WenFI
@path = C:\\Users\\antoine\\Documents\\projects\\school\\finalwork\\git\\PolyPrint3D\\divider\\demo.gcode.

# Test the root endpoint
GET {{baseUrl}}/
Accept: application/json

###

# Test the connect endpoint
GET {{baseUrl}}/connect?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the disconnect endpoint
GET {{baseUrl}}/disconnect?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the connection info endpoint
GET {{baseUrl}}/connection?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the flags endpoint
GET {{baseUrl}}/flags?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the bed temperature endpoint
GET {{baseUrl}}/temperature/bed?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the tool0 temperature endpoint
GET {{baseUrl}}/temperature/tool0?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the target bed temperature endpoint
GET {{baseUrl}}/temperature/bed/target?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the target tool0 temperature endpoint
GET {{baseUrl}}/temperature/tool0/target?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the job status endpoint
GET {{baseUrl}}/job/status?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the files endpoint
GET {{baseUrl}}/files?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###
# Test the upload endpoint
POST {{baseUrl}}/upload?ip={{ip}}&api_key={{apiKey}}&path={{path}}

###

# Test the delete endpoint
DELETE {{baseUrl}}/delete?ip={{ip}}&api_key={{apiKey}}&name=bottom_mesh_mount_0.15mm_PLA_MK3S_2h53m.gcode
Accept: application/json

###
POST {{baseUrl}}/select_file?ip={{ip}}&api_key={{apiKey}}&name=bottom_mesh_mount_0.15mm_PLA_MK3S_2h53m.gcode

###
POST {{baseUrl}}/job?ip={{ip}}&api_key={{apiKey}}

###
POST {{baseUrl}}/job/cancel?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###
POST {{baseUrl}}/job/pause?ip={{ip}}&api_key={{apiKey}}

###
POST {{baseUrl}}/job/resume?ip={{ip}}&api_key={{apiKey}}
