@baseUrl = http://127.0.0.1:8000
@ip = 10.0.0.254
#@ip = 10.2.168.3
@apiKey = hFswwTnAYX5NloewqL4MHfW_LyTqF7_GZ3qPB4WenFI
#@apiKey = uyyIkhKZuP8bqfLWv8OS5zBMS8AjIbnjqWEmwH9NRzo
@path = C:\\Users\\antoine\\Documents\\projects\\school\\finalwork\\git\\PolyPrint3D\\divider\\demo.gcode
# Test the root endpoint
GET {{baseUrl}}/
Accept: application/json

###

# Test the connect endpoint
GET {{baseUrl}}/connect?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the disconnect endpoint
GET {{baseUrl}}/disconnect?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the connection info endpoint
GET {{baseUrl}}/connection?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the flags endpoint
GET {{baseUrl}}/flags?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the bed temperature endpoint
GET {{baseUrl}}/temperature/bed?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the tool0 temperature endpoint
GET {{baseUrl}}/temperature/tool0?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the target bed temperature endpoint
GET {{baseUrl}}/temperature/bed/target?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the target tool0 temperature endpoint
GET {{baseUrl}}/temperature/tool0/target?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the job status endpoint
GET {{baseUrl}}/job/status?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###

# Test the files endpoint
GET {{baseUrl}}/files?ip={{ip}}&api_key={{apiKey}}
Accept: application/json

###
# Test the upload endpoint
POST {{baseUrl}}/upload?ip={{ip}}&api_key={{apiKey}}&path={{path}}

###

# Test the delete endpoint
DELETE {{baseUrl}}/delete?ip={{ip}}&api_key={{apiKey}}&name=demo.gcode
Accept: application/json







###
POST {{baseUrl}}/api/printer/command
Content-Type: application/json
Accept: application/json

{
  "ip": "{{ip}}",
  "api_key": "{{apiKey}}",
  "command": "M114"
}

###
# Test the job status endpoint
# Test the job cancel endpoint
POST {{baseUrl}}/job/cancel
Content-Type: application/json
Accept: application/json

{
  "ip": "{{ip}}",
  "api_key": "{{apiKey}}"
}
